- hosts: all
  sudo: yes
  roles:
    - { role: hadoop-common, mode: 'install' }

- hosts: namenode
  sudo: yes
  roles:
    - { role: hdfs-namenode, mode: 'install' }

- hosts: datanode
  sudo: yes
  roles:
    - { role: hdfs-datanode, mode: 'install' }

- hosts: resourcemanager
  sudo: yes
  roles:
    - { role: yarn-resourcemanager, mode: 'install' }

- hosts: nodemanager
  sudo: yes
  roles:
    - { role: yarn-nodemanager, mode: 'install' }

- hosts: localhost
  sudo: yes
  tasks:
    - name: generate the mapping file
      template: src=mapping.yml.j2 dest=./mapping.yml