- name: make sure the hadoop directories are available
  file: state=directory path={{ item }}
  with_items:
    - /data
    - /data/
    - /data/{{ tint.owner }}
    - /data/{{ tint.owner }}/{{ tint.id }}
    - /data/{{ tint.owner }}/{{ tint.id }}/config
    - /data/{{ tint.owner }}/{{ tint.id }}/data

- name: make sure the hadoop configuration is available
  template: src={{ item }} dest=/data/{{ tint.owner }}/{{ tint.id }}/config/{{ item }}
  with_items:
    - mapred-site.xml.template
    - configuration.xsl
    - hadoop-env.sh
    - httpfs-log4j.properties
    - core-site.xml
    - httpfs-signature.secret
    - hadoop-metrics.properties
    - yarn-site.xml
    - capacity-scheduler.xml
    - yarn-env.sh
    - httpfs-site.xml
    - httpfs-env.sh
    - log4j.properties
    - container-executor.cfg
    - mapred-env.sh
    - mapred-queues.xml.template
    - slaves
    - hdfs-site.xml
    - hadoop-policy.xml
    - hadoop-metrics2.properties
    - hadoop-env.cmd
    - mapred-site.xml
  tags:
    - config